name: Extractor Tests

on:
  pull_request:
    paths:
      - "riski-extractor/**"
      - ".github/workflows/extractor-tests.yml"

permissions:
  contents: read

jobs:
  extractor-tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres -d test_db"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=20

    env:
      RISKI__DB__NAME: test_db
      RISKI__DB__PASSWORD: password
      RISKI__DB__USER: postgres
      RISKI__DB__HOSTNAME: localhost
      RISKI__DB__PORT: 5432
      RISKI_EXTRACTOR__TEST__DB_NAME: test_db
      RISKI_EXTRACTOR__TEST__DB_USER: postgres
      RISKI_EXTRACTOR__TEST__DB_PASSWORD: postgres
      RISKI_EXTRACTOR__TEST__DB_HOSTNAME: localhost
      RISKI_EXTRACTOR__TEST__DB_PORT: "5432"
      OPENAI_API_KEY: example
      OPENAI_API_BASE: https://example.de
      OPENAI_API_VERSION: 2024-08-01-preview
      TIKTOKEN_CACHE_DIR: tiktoken_cache
      RISKI_OPENAI_EMBEDDING_MODEL: text-embedding-3-large

    defaults:
      run:
        working-directory: riski-extractor
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up uv
        uses: astral-sh/setup-uv@v4
        with:
          python-version-file: "riski-extractor/.python-version"

      - name: Install dependencies
        run: uv sync --group dev

      - name: Run extractor tests
        run: uv run pytest
