name: Extractor Tests

on:
  pull_request:
    paths:
      - "riski-extractor/**"
      - ".github/workflows/extractor-tests.yml"

permissions:
  contents: read

jobs:
  extractor-tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres -d test_db"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=20

    env:
      DATABASE_URL: postgresql+psycopg://postgres:postgres@localhost:5432/test_db
      DB_NAME: test_db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOSTNAME: localhost
      DB_PORT: "5432"

    defaults:
      run:
        working-directory: riski-extractor
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up uv
        uses: astral-sh/setup-uv@v4
        with:
          python-version-file: "riski-extractor/.python-version"

      - name: Install dependencies
        run: uv sync --group dev

      - name: Run extractor tests
        run: uv run pytest
